"$schema" = "https://starship.rs/config-schema.json"

format = "[]()$os[ ](inverted)[](bg:bright-blue)$directory[ ](fg:bright-blue)"

right_format = """
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
\
$package\
\
$bun\
$c\
$cpp\
$cmake\
$cobol\
$crystal\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$gradle\
$haskell\
$haxe\
$java\
$julia\
$kotlin\
$lua\
$meson\
$mojo\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$perl\
$php\
$purescript\
$python\
$quarto\
$raku\
$red\
$rlang\
$ruby\
$rust\
$scala\
$solidity\
$spack\
$swift\
$typst\
$vlang\
$zig\
\
$aws\
$azure\
$buf\
$conda\
$container\
$docker_context\
$gcloud\
$helm\
$kubernetes\
$nix_shell\
$guix_shell\
$openstack\
$pulumi\
$singularity\
$terraform\
$vagrant\
$pixi\
$mise\
\
$battery\
$cmd_duration\
$status\
\
$jobs\
$username\
$hostname\
$localip\
$shlvl\
$memory_usage\
$env_var\
$custom\
$direnv\
$shell\
$sudo\
"""

[os]
disabled = false
format = "[$symbol](inverted)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
NixOS = ""
EndeavourOS = ""
Void = ""
FreeBSD = ""
OpenBSD = "󰈺"

[directory]
format = "[ ($read_only )$path ](inverted fg:bright-blue)"
read_only = "󰌾"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
"home_symbol" = "󰋜 "

[directory.substitutions]
# "/Documents/" = "/ 󰈙 /"
# "/Downloads/" = "/  /"
# "/Music/" = "/ 󰝚 /"
# "/Pictures/" = "/  /"
# "/Developer/" = "/  /"
# "/Programming/" = "/  /"
# "/Games/" = "/ 󰊗 /"
# "/Videos/" = "/ 󰕧 /"
# "/Experiments/" = "/  /"
# "/School/" = "/ 󰑴 /"
# "/Projects/" = "/  /"
# "/Desktop/" = "/ 󰇄 /"

# Version Control Systems
[git_branch]
only_attached = false
always_show_remote = false
ignore_branches = []
symbol = ""
style = "fg:green"
format = "[]($style)[$symbol $branch(:$remote_branch) ]($style inverted)"

[git_commit]
style = "fg:green"
format = "[\\($hash$tag\\) ]($style inverted)"

[git_state]
style = "fg:green"
format = "[\\($state( $progress_current/$progress_total)\\) ]($style inverted)"

[git_metrics]
disabled = true

[git_status]
style = "fg:green"
format = "[($all_status$ahead_behind)]($style inverted)[]($style)"

[hg_branch]
disabled=true
symbol = ""
style = "fg:green"
format = "[]($style)[$symbol $branch(:$topic)]($style inverted)[]($style)"

[hg_state]
disabled=true

[pijul_channel]
disabled=true
symbol = ""
style = "fg:green"
format = "[]($style)[$symbol $channel]($style inverted)[]($style)"

[fossil_branch]
disabled=true
symbol = ""
style = "fg:green"
format = "[]($style)[$symbol $branch]($style inverted)[]($style)"

[fossil_metrics]
disabled=true

# Containers, Cloud & Infrastructure
[docker_context]
symbol = ""
style = "fg:bright-purple"
format = "[]($style)[$symbol( $context)]($style inverted)[]($style)"

[container]
symbol = "󰆦"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $name)]($style inverted)[]($style)"

[gcloud]
disabled=true
symbol = "󱇶"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $account)(:$project)]($style inverted)[]($style)"

[aws]
symbol = "󰸏"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $profile)(:$region)]($style inverted)[]($style)"

[azure]
disabled=true
symbol = "󰠅"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $subscription)]($style inverted)[]($style)"

[kubernetes]
disabled = false
symbol = "󱃾"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $context)(:$namespace)]($style inverted)[]($style)"

[terraform]
symbol = "󱁢"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $workspace)]($style inverted)[]($style)"

[helm]
symbol = "⎈"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[openstack]
symbol = "󰢤"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $cloud)(:$project)]($style inverted)[]($style)"

[pulumi]
symbol = ""
style = "fg:bright-purple"
format = "[]($style)[$symbol( $username@)$stack]($style inverted)[]($style)"

[singularity]
symbol = "󰆦"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $env)]($style inverted)[]($style)"

[vagrant]
symbol = ""
style = "fg:bright-purple"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[conda]
symbol = ""
style = "fg:bright-purple"
format = "[]($style)[$symbol( $environment)]($style inverted)[]($style)"

[buf]
symbol = ""
style = "fg:bright-purple"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[nix_shell]
symbol = ""
style = "fg:bright-purple"
format = "[]($style)[$symbol( $state)( $name)]($style inverted)[]($style)"

[guix_shell]
symbol = ""
style = "fg:bright-purple"
format = "[]($style)[$symbol]($style inverted)[]($style)"

[pixi]
symbol = "󰏗"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $version)( $environment)]($style inverted)[]($style)"

[mise]
disabled=true
symbol = "󰒲"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $health)]($style inverted)[]($style)"

# Package Managers
[package]
symbol = "󰏖"
style = "fg:bright-yellow"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[spack]
symbol = "󰏖"
style = "fg:cyan"
format = "[]($style)[$symbol( $environment)]($style inverted)[]($style)"

# Programming Languages & Runtimes
[dotnet]
symbol = "󰌛"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)( 🎯 $tfm)]($style inverted)[]($style)"

[nodejs]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[bun]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[deno]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[c]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version(-$name))]($style inverted)[]($style)"

[cpp]
disabled=false
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version(-$name))]($style inverted)[]($style)"

[cmake]
symbol = "󰔶"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[rust]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[golang]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[php]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[java]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[kotlin]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[gradle]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[haskell]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[python]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)( $virtualenv)]($style inverted)[]($style)"

[ruby]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[lua]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[swift]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[zig]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[dart]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[elixir]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)( OTP $otp_version)]($style inverted)[]($style)"

[elm]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[erlang]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[fennel]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[gleam]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[haxe]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[julia]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[nim]
symbol = "󰆥"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[ocaml]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)( $switch_name)]($style inverted)[]($style)"

[odin]
symbol = "󰈺"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[opa]
symbol = "󰈸"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[perl]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[purescript]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[quarto]
symbol = "󱓧"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[raku]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)(-$vm_version)]($style inverted)[]($style)"

[red]
symbol = "🔺"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[rlang]
symbol = "󰟔"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[scala]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[solidity]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[typst]
symbol = "󰲰"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[vlang]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[crystal]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[daml]
symbol = "λ"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[cobol]
symbol = "⚙"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[meson]
symbol = "󰔷"
style = "fg:cyan"
format = "[]($style)[$symbol( $project)]($style inverted)[]($style)"

[mojo]
symbol = "🔥"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

# System, Shell & Session
[username]
style_user = "fg:yellow"
style_root = "fg:red"
format = "[]($style)[$user]($style inverted)[]($style)"

[hostname]
ssh_only = true
ssh_symbol = "󰖩"
style = "fg:green"
format = "[]($style)[$ssh_symbol]($style inverted)[]($style)"

[localip]
disabled=false
ssh_only = true
format = "[]($style)[$localipv4]($style inverted)[]($style)"
style = "fg:green"

[time]
disabled = true

[line_break]
disabled = true

[character]
success_symbol = "[❯](bold fg:blue)"

[cmd_duration]
min_time = 100
style = "fg:bright-blue"
format = "[]($style)[$duration]($style inverted)[]($style)"

[status]
disabled = false
symbol = ""
style = "fg:red"
format = "[]($style)[$symbol $status]($style inverted)[]($style)"

[memory_usage]
disabled=true
symbol = "󰍛"
style = "fg:bright-blue"
format = "[]($style)[$symbol $ram( | $swap)]($style inverted)[]($style)"

[jobs]
symbol = "✦"
style = "fg:bright-blue"
format = "[]($style)[$symbol $number]($style inverted)[]($style)"

[sudo]
disabled=false
symbol = "󰌋"
style = "fg:bright-red"
format = "[]($style)[$symbol]($style inverted)[]($style)"

[shlvl]
disabled=true
symbol = "󰘍"
style = "fg:bright-blue"
format = "[]($style)[$symbol$shlvl]($style inverted)[]($style)"

[direnv]
disabled=false
symbol = "󰌪"
style = "fg:bright-blue"
format = "[]($style)[$symbol( $loaded/$allowed)]($style inverted)[]($style)"

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁽 "
empty_symbol = "󰂎 "
format = "[]($style)[$symbol$percentage]($style inverted)[]($style)"

[[battery.display]]
threshold = 20
style = "fg:bright-red"
